name: reusable workflow for automated tests running
on:
  push:
    branches: [main]
  pull_request:
    branches : [main]
jobs:
  run-automated-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
          
    - name: Maven verify
      run: mvn -B clean verify
       
    - name: Retry on failure
      if:  ${{ steps.mavenStep.outcome=='failure' && inputs.retry-on-failure==true }}   
      run: |
        echo "Waitnng 60 seconds to retry ..."
        sleep 60
        mvn -B clean verify -Dcucumber.filter.tags="${{ inputs.tags }}" -Denvironment=${{ inputs.environment }} -DgridUrl=https://selenium-grid.app.cision.com/wd/hub -Dbrowser=${{ inputs.browser }}
   
        
    - name: report artifact - cucumber report  
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: "${{ github.workflow }}${{ inputs.invoker }}-cucumberReport"
        path: target/cucumber-reports/
